### ISSUE TITLE
AT fails to start on working directory change

### ISSUE THREAD

**Issue by markojaadam** [AlgoTaurus/algotaurus#37]
AlgoTaurus fails to start when user changes the working directory (eg. from the Windows shortcut). One possible reason is that the paths of the additional files (pictures, icons, locales) are not properly configured and the program looks for them always in the working directory.
This issue has to be resolved to build Linux installer.

**Comment by krajcsi** [comment]
There is no reasonable use case why the user would want to change the working directory. So I close this bug. If this should be fixed for the Linux installer, that's another problem.
